function Get-PHTheme {
    <#
    .SYNOPSIS
      Retrieve a predefined theme configuration by name.
    .DESCRIPTION
      Returns a hashtable defining terminal colors, styles, borders and layouts.
      Gradient themes additionally expose GradientSteps (int[]) and GradientType ('fg'|'bg')
      keys that callers can pass directly to New-AsciiGradient.
    .PARAMETER Name
      Name of the theme. Default is 'default'.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Position = 0)]
        [string]$Name = 'default'
    )

    # ── Original 10 themes ────────────────────────────────────────────────────
    $Themes = @{
        'default' = @{
            AccentColor      = 'darkgreen'
            AccentFormat     = 'bold,italic'
            BorderColor      = 'darkgreen'
            BorderFormat     = 'bold'
            HeaderBg         = 'gray'
            HeaderFg         = 'cyan'
            ModuleBg         = 'gray'
            ModuleFg         = 'cyan'
            VersionBg        = 'gray'
            VersionFg        = 'darkmagenta'
            SyntaxFg         = 'white'
            SyntaxFormat     = 'none'
            DescriptionFg    = 'white'
            ParamNameFg      = 'darkmagenta'
            ParamNameFormat  = 'none'
            ParamTypeFg      = 'darkcyan'
            ParamTypeFormat  = 'none'
            ParamReqFg       = 'red'
            ParamReqFormat   = 'bold'
            ParamDescFg      = 'gray'
            ExampleFg        = 'gray'
            DocsFg           = 'darkcyan'
            DocsFormat       = 'bold,underline'
            SectionChar      = '◉'
            HeaderChar       = '▶'
            BorderTop        = '▫▫▫▫▫▫▫▫════════════════════════════════════════════════════════▫▫▫▫▫▫═╗'
            BorderBottom     = '▫▫▫▫▫▫▫▫════════════════════════════════════════════════════════▫▫▫▫▫▫═╝'
            BorderMiddle     = '░'
        }
        'matrix' = @{
            AccentColor      = 'green'
            AccentFormat     = 'bold'
            BorderColor      = 'green'
            BorderFormat     = 'bold'
            HeaderBg         = 'black'
            HeaderFg         = 'green'
            ModuleBg         = 'black'
            ModuleFg         = 'green'
            VersionBg        = 'black'
            VersionFg        = 'green'
            SyntaxFg         = 'green'
            SyntaxFormat     = 'none'
            DescriptionFg    = 'green'
            ParamNameFg      = 'green'
            ParamNameFormat  = 'bold'
            ParamTypeFg      = 'green'
            ParamTypeFormat  = 'italic'
            ParamReqFg       = 'green'
            ParamReqFormat   = 'reverse'
            ParamDescFg      = 'gray'
            ExampleFg        = 'green'
            DocsFg           = 'green'
            DocsFormat       = 'underline'
            SectionChar      = '$'
            HeaderChar       = '>'
            BorderTop        = '┌────────────────────────────────────────────────────────┐'
            BorderBottom     = '└────────────────────────────────────────────────────────┘'
            BorderMiddle     = ' '
        }
        'cyberpunk' = @{
            AccentColor      = 'magenta'
            AccentFormat     = 'bold'
            BorderColor      = 'cyan'
            BorderFormat     = 'bold'
            HeaderBg         = 'black'
            HeaderFg         = 'yellow'
            ModuleBg         = 'black'
            ModuleFg         = 'magenta'
            VersionBg        = 'black'
            VersionFg        = 'cyan'
            SyntaxFg         = 'white'
            SyntaxFormat     = 'none'
            DescriptionFg    = 'yellow'
            ParamNameFg      = 'magenta'
            ParamNameFormat  = 'bold'
            ParamTypeFg      = 'cyan'
            ParamTypeFormat  = 'none'
            ParamReqFg       = 'red'
            ParamReqFormat   = 'bold'
            ParamDescFg      = 'gray'
            ExampleFg        = 'cyan'
            DocsFg           = 'yellow'
            DocsFormat       = 'bold,underline'
            SectionChar      = '▲'
            HeaderChar       = '»'
            BorderTop        = '⚡════════════════════════════════════════════════════════════⚡'
            BorderBottom     = '⚡════════════════════════════════════════════════════════════⚡'
            BorderMiddle     = '░'
        }
        'dracula' = @{
            AccentColor      = 'magenta'
            AccentFormat     = 'bold'
            BorderColor      = 'magenta'
            BorderFormat     = 'none'
            HeaderBg         = 'black'
            HeaderFg         = 'blue'
            ModuleBg         = 'black'
            ModuleFg         = 'blue'
            VersionBg        = 'black'
            VersionFg        = 'yellow'
            SyntaxFg         = 'white'
            SyntaxFormat     = 'none'
            DescriptionFg    = 'green'
            ParamNameFg      = 'magenta'
            ParamNameFormat  = 'none'
            ParamTypeFg      = 'cyan'
            ParamTypeFormat  = 'italic'
            ParamReqFg       = 'red'
            ParamReqFormat   = 'bold'
            ParamDescFg      = 'gray'
            ExampleFg        = 'yellow'
            DocsFg           = 'cyan'
            DocsFormat       = 'underline'
            SectionChar      = '🧛'
            HeaderChar       = '→'
            BorderTop        = '░░░░▒▒▒▒▓▓▓▓───────────────────────────────────▓▓▓▓▒▒▒▒░░░░'
            BorderBottom     = '░░░░▒▒▒▒▓▓▓▓───────────────────────────────────▓▓▓▓▒▒▒▒░░░░'
            BorderMiddle     = '🦇'
        }
        'nord' = @{
            AccentColor      = 'blue'
            AccentFormat     = 'bold'
            BorderColor      = 'darkblue'
            BorderFormat     = 'none'
            HeaderBg         = 'gray'
            HeaderFg         = 'white'
            ModuleBg         = 'gray'
            ModuleFg         = 'cyan'
            VersionBg        = 'gray'
            VersionFg        = 'blue'
            SyntaxFg         = 'white'
            SyntaxFormat     = 'none'
            DescriptionFg    = 'white'
            ParamNameFg      = 'blue'
            ParamNameFormat  = 'bold'
            ParamTypeFg      = 'cyan'
            ParamTypeFormat  = 'none'
            ParamReqFg       = 'red'
            ParamReqFormat   = 'none'
            ParamDescFg      = 'gray'
            ExampleFg        = 'cyan'
            DocsFg           = 'blue'
            DocsFormat       = 'underline'
            SectionChar      = '❄'
            HeaderChar       = '›'
            BorderTop        = '❄────────────────────────────────────────────────────────❄'
            BorderBottom     = '❄────────────────────────────────────────────────────────❄'
            BorderMiddle     = '·'
        }
        'monokai' = @{
            AccentColor      = 'green'
            AccentFormat     = 'bold'
            BorderColor      = 'yellow'
            BorderFormat     = 'none'
            HeaderBg         = 'black'
            HeaderFg         = 'magenta'
            ModuleBg         = 'black'
            ModuleFg         = 'magenta'
            VersionBg        = 'black'
            VersionFg        = 'yellow'
            SyntaxFg         = 'white'
            SyntaxFormat     = 'none'
            DescriptionFg    = 'white'
            ParamNameFg      = 'magenta'
            ParamNameFormat  = 'bold'
            ParamTypeFg      = 'cyan'
            ParamTypeFormat  = 'italic'
            ParamReqFg       = 'red'
            ParamReqFormat   = 'bold'
            ParamDescFg      = 'gray'
            ExampleFg        = 'yellow'
            DocsFg           = 'green'
            DocsFormat       = 'underline'
            SectionChar      = '❖'
            HeaderChar       = '»'
            BorderTop        = '==========================================================='
            BorderBottom     = '==========================================================='
            BorderMiddle     = ' '
        }
        'solarized' = @{
            AccentColor      = 'cyan'
            AccentFormat     = 'bold'
            BorderColor      = 'blue'
            BorderFormat     = 'none'
            HeaderBg         = 'black'
            HeaderFg         = 'yellow'
            ModuleBg         = 'black'
            ModuleFg         = 'cyan'
            VersionBg        = 'black'
            VersionFg        = 'magenta'
            SyntaxFg         = 'white'
            SyntaxFormat     = 'none'
            DescriptionFg    = 'gray'
            ParamNameFg      = 'blue'
            ParamNameFormat  = 'none'
            ParamTypeFg      = 'green'
            ParamTypeFormat  = 'none'
            ParamReqFg       = 'red'
            ParamReqFormat   = 'bold'
            ParamDescFg      = 'gray'
            ExampleFg        = 'green'
            DocsFg           = 'cyan'
            DocsFormat       = 'underline'
            SectionChar      = '☼'
            HeaderChar       = '☞'
            BorderTop        = '☼────────────────────────────────────────────────────────☼'
            BorderBottom     = '☼────────────────────────────────────────────────────────☼'
            BorderMiddle     = ' '
        }
        'sunset' = @{
            AccentColor      = 'red'
            AccentFormat     = 'bold'
            BorderColor      = 'yellow'
            BorderFormat     = 'bold'
            HeaderBg         = 'gray'
            HeaderFg         = 'red'
            ModuleBg         = 'gray'
            ModuleFg         = 'yellow'
            VersionBg        = 'gray'
            VersionFg        = 'magenta'
            SyntaxFg         = 'white'
            SyntaxFormat     = 'none'
            DescriptionFg    = 'yellow'
            ParamNameFg      = 'red'
            ParamNameFormat  = 'bold'
            ParamTypeFg      = 'yellow'
            ParamTypeFormat  = 'none'
            ParamReqFg       = 'red'
            ParamReqFormat   = 'bold'
            ParamDescFg      = 'gray'
            ExampleFg        = 'yellow'
            DocsFg           = 'red'
            DocsFormat       = 'underline'
            SectionChar      = '🌅'
            HeaderChar       = '➔'
            BorderTop        = '🌅━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━🌅'
            BorderBottom     = '🌅━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━🌅'
            BorderMiddle     = '▒'
        }
        'forest' = @{
            AccentColor      = 'darkgreen'
            AccentFormat     = 'bold'
            BorderColor      = 'green'
            BorderFormat     = 'none'
            HeaderBg         = 'black'
            HeaderFg         = 'green'
            ModuleBg         = 'black'
            ModuleFg         = 'darkgreen'
            VersionBg        = 'black'
            VersionFg        = 'yellow'
            SyntaxFg         = 'white'
            SyntaxFormat     = 'none'
            DescriptionFg    = 'gray'
            ParamNameFg      = 'green'
            ParamNameFormat  = 'bold'
            ParamTypeFg      = 'darkyellow'
            ParamTypeFormat  = 'italic'
            ParamReqFg       = 'red'
            ParamReqFormat   = 'bold'
            ParamDescFg      = 'gray'
            ExampleFg        = 'green'
            DocsFg           = 'darkgreen'
            DocsFormat       = 'underline'
            SectionChar      = '🌲'
            HeaderChar       = '🌿'
            BorderTop        = '🌲━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━🌲'
            BorderBottom     = '🌲━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━🌲'
            BorderMiddle     = '✿'
        }
        'classic' = @{
            AccentColor      = 'white'
            AccentFormat     = 'bold,underline'
            BorderColor      = 'white'
            BorderFormat     = 'none'
            HeaderBg         = ''
            HeaderFg         = 'white'
            ModuleBg         = ''
            ModuleFg         = 'white'
            VersionBg        = ''
            VersionFg        = 'white'
            SyntaxFg         = 'white'
            SyntaxFormat     = 'none'
            DescriptionFg    = 'white'
            ParamNameFg      = 'white'
            ParamNameFormat  = 'bold'
            ParamTypeFg      = 'white'
            ParamTypeFormat  = 'underline'
            ParamReqFg       = 'white'
            ParamReqFormat   = 'bold'
            ParamDescFg      = 'white'
            ExampleFg        = 'white'
            DocsFg           = 'white'
            DocsFormat       = 'underline'
            SectionChar      = ''
            HeaderChar       = ''
            BorderTop        = '------------------------------------------------------------'
            BorderBottom     = '------------------------------------------------------------'
            BorderMiddle     = ' '
        }
    }

    # ── 10 new gradient-capable themes ────────────────────────────────────────
    # Each theme includes:
    #   GradientSteps  – int[] of 256-color palette stops for New-AsciiGradient
    #   GradientType   – 'fg' (foreground gradient)
    # All standard color keys are present for fallback with New-AsciiColor.

    # 1. aurora — Northern lights: cyan → purple → magenta
    $Themes['aurora'] = @{
        AccentColor      = 'cyan'
        AccentFormat     = 'bold'
        BorderColor      = 'magenta'
        BorderFormat     = 'bold'
        HeaderBg         = 'black'
        HeaderFg         = 'cyan'
        ModuleBg         = 'black'
        ModuleFg         = 'cyan'
        VersionBg        = 'black'
        VersionFg        = 'magenta'
        SyntaxFg         = 'white'
        SyntaxFormat     = 'none'
        DescriptionFg    = 'cyan'
        ParamNameFg      = 'magenta'
        ParamNameFormat  = 'bold'
        ParamTypeFg      = 'cyan'
        ParamTypeFormat  = 'italic'
        ParamReqFg       = 'red'
        ParamReqFormat   = 'bold'
        ParamDescFg      = 'gray'
        ExampleFg        = 'cyan'
        DocsFg           = 'magenta'
        DocsFormat       = 'underline'
        SectionChar      = '✦'
        HeaderChar       = '◈'
        BorderTop        = '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━'
        BorderBottom     = '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━'
        BorderMiddle     = '·'
        GradientSteps    = [int[]]@(51, 93, 129, 201)
        GradientType     = 'fg'
    }

    # 2. neon-noir — Dark pink/purple neon: magenta → deep pink
    $Themes['neon-noir'] = @{
        AccentColor      = 'magenta'
        AccentFormat     = 'bold'
        BorderColor      = 'magenta'
        BorderFormat     = 'bold'
        HeaderBg         = 'black'
        HeaderFg         = 'magenta'
        ModuleBg         = 'black'
        ModuleFg         = 'magenta'
        VersionBg        = 'black'
        VersionFg        = 'red'
        SyntaxFg         = 'white'
        SyntaxFormat     = 'none'
        DescriptionFg    = 'magenta'
        ParamNameFg      = 'magenta'
        ParamNameFormat  = 'bold'
        ParamTypeFg      = 'red'
        ParamTypeFormat  = 'italic'
        ParamReqFg       = 'red'
        ParamReqFormat   = 'bold'
        ParamDescFg      = 'gray'
        ExampleFg        = 'magenta'
        DocsFg           = 'red'
        DocsFormat       = 'underline'
        SectionChar      = '◆'
        HeaderChar       = '⟩'
        BorderTop        = '◆══════════════════════════════════════════════════════════◆'
        BorderBottom     = '◆══════════════════════════════════════════════════════════◆'
        BorderMiddle     = '░'
        GradientSteps    = [int[]]@(201, 198, 196, 200)
        GradientType     = 'fg'
    }

    # 3. lava — Hot reds/oranges: red → orange → yellow
    $Themes['lava'] = @{
        AccentColor      = 'red'
        AccentFormat     = 'bold'
        BorderColor      = 'yellow'
        BorderFormat     = 'bold'
        HeaderBg         = 'black'
        HeaderFg         = 'red'
        ModuleBg         = 'black'
        ModuleFg         = 'yellow'
        VersionBg        = 'black'
        VersionFg        = 'yellow'
        SyntaxFg         = 'white'
        SyntaxFormat     = 'none'
        DescriptionFg    = 'yellow'
        ParamNameFg      = 'red'
        ParamNameFormat  = 'bold'
        ParamTypeFg      = 'yellow'
        ParamTypeFormat  = 'none'
        ParamReqFg       = 'red'
        ParamReqFormat   = 'bold'
        ParamDescFg      = 'gray'
        ExampleFg        = 'yellow'
        DocsFg           = 'red'
        DocsFormat       = 'underline'
        SectionChar      = '🔥'
        HeaderChar       = '▶'
        BorderTop        = '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━'
        BorderBottom     = '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━'
        BorderMiddle     = '▒'
        GradientSteps    = [int[]]@(196, 202, 214, 220)
        GradientType     = 'fg'
    }

    # 4. ocean — Deep sea: dark blue → cyan
    $Themes['ocean'] = @{
        AccentColor      = 'darkblue'
        AccentFormat     = 'bold'
        BorderColor      = 'cyan'
        BorderFormat     = 'none'
        HeaderBg         = 'black'
        HeaderFg         = 'cyan'
        ModuleBg         = 'black'
        ModuleFg         = 'cyan'
        VersionBg        = 'black'
        VersionFg        = 'blue'
        SyntaxFg         = 'white'
        SyntaxFormat     = 'none'
        DescriptionFg    = 'cyan'
        ParamNameFg      = 'blue'
        ParamNameFormat  = 'bold'
        ParamTypeFg      = 'cyan'
        ParamTypeFormat  = 'italic'
        ParamReqFg       = 'red'
        ParamReqFormat   = 'bold'
        ParamDescFg      = 'gray'
        ExampleFg        = 'cyan'
        DocsFg           = 'blue'
        DocsFormat       = 'underline'
        SectionChar      = '≈'
        HeaderChar       = '◦'
        BorderTop        = '≈────────────────────────────────────────────────────────≈'
        BorderBottom     = '≈────────────────────────────────────────────────────────≈'
        BorderMiddle     = '·'
        GradientSteps    = [int[]]@(17, 20, 27, 39, 51)
        GradientType     = 'fg'
    }

    # 5. toxic — Acid green: bright greens
    $Themes['toxic'] = @{
        AccentColor      = 'green'
        AccentFormat     = 'bold'
        BorderColor      = 'green'
        BorderFormat     = 'bold'
        HeaderBg         = 'black'
        HeaderFg         = 'green'
        ModuleBg         = 'black'
        ModuleFg         = 'green'
        VersionBg        = 'black'
        VersionFg        = 'green'
        SyntaxFg         = 'white'
        SyntaxFormat     = 'none'
        DescriptionFg    = 'green'
        ParamNameFg      = 'green'
        ParamNameFormat  = 'bold'
        ParamTypeFg      = 'green'
        ParamTypeFormat  = 'italic'
        ParamReqFg       = 'red'
        ParamReqFormat   = 'bold'
        ParamDescFg      = 'gray'
        ExampleFg        = 'green'
        DocsFg           = 'green'
        DocsFormat       = 'underline'
        SectionChar      = '⚗'
        HeaderChar       = '⊲'
        BorderTop        = '────────────────────────────────────────────────────────────'
        BorderBottom     = '────────────────────────────────────────────────────────────'
        BorderMiddle     = '·'
        GradientSteps    = [int[]]@(46, 82, 118, 154)
        GradientType     = 'fg'
    }

    # 6. midnight — Deep indigo/purple: deep blue → violet
    $Themes['midnight'] = @{
        AccentColor      = 'darkblue'
        AccentFormat     = 'bold'
        BorderColor      = 'darkmagenta'
        BorderFormat     = 'none'
        HeaderBg         = 'black'
        HeaderFg         = 'blue'
        ModuleBg         = 'black'
        ModuleFg         = 'magenta'
        VersionBg        = 'black'
        VersionFg        = 'magenta'
        SyntaxFg         = 'white'
        SyntaxFormat     = 'none'
        DescriptionFg    = 'blue'
        ParamNameFg      = 'magenta'
        ParamNameFormat  = 'bold'
        ParamTypeFg      = 'blue'
        ParamTypeFormat  = 'italic'
        ParamReqFg       = 'red'
        ParamReqFormat   = 'bold'
        ParamDescFg      = 'gray'
        ExampleFg        = 'blue'
        DocsFg           = 'magenta'
        DocsFormat       = 'underline'
        SectionChar      = '★'
        HeaderChar       = '◇'
        BorderTop        = '············································································'
        BorderBottom     = '············································································'
        BorderMiddle     = '·'
        GradientSteps    = [int[]]@(17, 54, 91, 128, 165)
        GradientType     = 'fg'
    }

    # 7. gold — Gold/copper: dark gold → yellow
    $Themes['gold'] = @{
        AccentColor      = 'yellow'
        AccentFormat     = 'bold'
        BorderColor      = 'yellow'
        BorderFormat     = 'bold'
        HeaderBg         = 'black'
        HeaderFg         = 'yellow'
        ModuleBg         = 'black'
        ModuleFg         = 'yellow'
        VersionBg        = 'black'
        VersionFg        = 'yellow'
        SyntaxFg         = 'white'
        SyntaxFormat     = 'none'
        DescriptionFg    = 'yellow'
        ParamNameFg      = 'yellow'
        ParamNameFormat  = 'bold'
        ParamTypeFg      = 'yellow'
        ParamTypeFormat  = 'italic'
        ParamReqFg       = 'red'
        ParamReqFormat   = 'bold'
        ParamDescFg      = 'gray'
        ExampleFg        = 'yellow'
        DocsFg           = 'yellow'
        DocsFormat       = 'underline'
        SectionChar      = '◈'
        HeaderChar       = '►'
        BorderTop        = '◈────────────────────────────────────────────────────────◈'
        BorderBottom     = '◈────────────────────────────────────────────────────────◈'
        BorderMiddle     = '·'
        GradientSteps    = [int[]]@(136, 172, 214, 220, 226)
        GradientType     = 'fg'
    }

    # 8. rose — Pink/rose: deep pink → light pink
    $Themes['rose'] = @{
        AccentColor      = 'magenta'
        AccentFormat     = 'bold'
        BorderColor      = 'magenta'
        BorderFormat     = 'none'
        HeaderBg         = 'black'
        HeaderFg         = 'magenta'
        ModuleBg         = 'black'
        ModuleFg         = 'magenta'
        VersionBg        = 'black'
        VersionFg        = 'magenta'
        SyntaxFg         = 'white'
        SyntaxFormat     = 'none'
        DescriptionFg    = 'magenta'
        ParamNameFg      = 'magenta'
        ParamNameFormat  = 'bold'
        ParamTypeFg      = 'magenta'
        ParamTypeFormat  = 'italic'
        ParamReqFg       = 'red'
        ParamReqFormat   = 'bold'
        ParamDescFg      = 'gray'
        ExampleFg        = 'magenta'
        DocsFg           = 'magenta'
        DocsFormat       = 'underline'
        SectionChar      = '✿'
        HeaderChar       = '›'
        BorderTop        = '✿────────────────────────────────────────────────────────✿'
        BorderBottom     = '✿────────────────────────────────────────────────────────✿'
        BorderMiddle     = '·'
        GradientSteps    = [int[]]@(161, 197, 199, 207, 213)
        GradientType     = 'fg'
    }

    # 9. steel — Greyscale metallic: dark → light grey
    $Themes['steel'] = @{
        AccentColor      = 'gray'
        AccentFormat     = 'bold'
        BorderColor      = 'gray'
        BorderFormat     = 'none'
        HeaderBg         = 'black'
        HeaderFg         = 'white'
        ModuleBg         = 'black'
        ModuleFg         = 'gray'
        VersionBg        = 'black'
        VersionFg        = 'white'
        SyntaxFg         = 'white'
        SyntaxFormat     = 'none'
        DescriptionFg    = 'gray'
        ParamNameFg      = 'white'
        ParamNameFormat  = 'bold'
        ParamTypeFg      = 'gray'
        ParamTypeFormat  = 'italic'
        ParamReqFg       = 'red'
        ParamReqFormat   = 'bold'
        ParamDescFg      = 'gray'
        ExampleFg        = 'gray'
        DocsFg           = 'white'
        DocsFormat       = 'underline'
        SectionChar      = '▪'
        HeaderChar       = '▸'
        BorderTop        = '────────────────────────────────────────────────────────────'
        BorderBottom     = '────────────────────────────────────────────────────────────'
        BorderMiddle     = '·'
        GradientSteps    = [int[]]@(233, 238, 243, 248, 253)
        GradientType     = 'fg'
    }

    # 11. glitch — Cyber-punk glitchy
    $Themes['glitch'] = @{
        AccentColor      = '198'
        AccentFormat     = 'bold'
        BorderColor      = '45'
        BorderFormat     = 'bold'
        HeaderBg         = 'black'
        HeaderFg         = '198'
        ModuleBg         = 'black'
        ModuleFg         = '45'
        VersionBg        = 'black'
        VersionFg        = '51'
        SyntaxFg         = 'white'
        SyntaxFormat     = 'none'
        DescriptionFg    = '198'
        ParamNameFg      = '45'
        ParamNameFormat  = 'bold'
        ParamTypeFg      = '51'
        ParamTypeFormat  = 'italic'
        ParamReqFg       = '201'
        ParamReqFormat   = 'reverse'
        ParamDescFg      = 'gray'
        ExampleFg        = '51'
        DocsFg           = '198'
        DocsFormat       = 'underline'
        SectionChar      = '▚'
        HeaderChar       = '▞'
        BorderTop        = '▚▞▚▞▚▞▚▞▚▞▚▞▚▞▚▞▚▞▚▞▚▞▚▞▚▞▚▞▚▞▚▞▚▞▚▞▚▞▚▞▚▞▚▞'
        BorderBottom     = '▚▞▚▞▚▞▚▞▚▞▚▞▚▞▚▞▚▞▚▞▚▞▚▞▚▞▚▞▚▞▚▞▚▞▚▞▚▞▚▞▚▞▚▞'
        BorderMiddle     = '▞'
        GradientSteps    = [int[]]@(196, 201, 45, 51)
        GradientType     = 'fg'
    }

    # 12. cosmic — Space/starry night
    $Themes['cosmic'] = @{
        AccentColor      = '105'
        AccentFormat     = 'bold'
        BorderColor      = '18'
        BorderFormat     = 'none'
        HeaderBg         = 'black'
        HeaderFg         = '129'
        ModuleBg         = 'black'
        ModuleFg         = '93'
        VersionBg        = 'black'
        VersionFg        = '105'
        SyntaxFg         = 'white'
        SyntaxFormat     = 'none'
        DescriptionFg    = '93'
        ParamNameFg      = '129'
        ParamNameFormat  = 'bold'
        ParamTypeFg      = '105'
        ParamTypeFormat  = 'italic'
        ParamReqFg       = '93'
        ParamReqFormat   = 'bold'
        ParamDescFg      = 'gray'
        ExampleFg        = '105'
        DocsFg           = '129'
        DocsFormat       = 'underline'
        SectionChar      = '☄'
        HeaderChar       = '★'
        BorderTop        = '★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆'
        BorderBottom     = '★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆'
        BorderMiddle     = '·'
        GradientSteps    = [int[]]@(17, 21, 57, 93, 129)
        GradientType     = 'fg'
    }

    # 13. forest-mist — Earthy green/moss
    $Themes['forest-mist'] = @{
        AccentColor      = '28'
        AccentFormat     = 'bold,italic'
        BorderColor      = '240'
        BorderFormat     = 'none'
        HeaderBg         = 'black'
        HeaderFg         = '64'
        ModuleBg         = 'black'
        ModuleFg         = '28'
        VersionBg        = 'black'
        VersionFg        = '106'
        SyntaxFg         = 'white'
        SyntaxFormat     = 'none'
        DescriptionFg    = '244'
        ParamNameFg      = '64'
        ParamNameFormat  = 'bold'
        ParamTypeFg      = '28'
        ParamTypeFormat  = 'italic'
        ParamReqFg       = '106'
        ParamReqFormat   = 'bold'
        ParamDescFg      = 'gray'
        ExampleFg        = '106'
        DocsFg           = '64'
        DocsFormat       = 'underline'
        SectionChar      = '🍀'
        HeaderChar       = '🌿'
        BorderTop        = '┋ ┄ ┅ ┄ ┅ ┄ ┅ ┄ ┅ ┄ ┅ ┄ ┅ ┄ ┅ ┄ ┅ ┄ ┅ ┄ ┅ ┄ ┅ ┄ ┅ ┄ ┅ ┋'
        BorderBottom     = '┋ ┄ ┅ ┄ ┅ ┄ ┅ ┄ ┅ ┄ ┅ ┄ ┅ ┄ ┅ ┄ ┅ ┄ ┅ ┄ ┅ ┄ ┅ ┄ ┅ ┄ ┅ ┋'
        BorderMiddle     = '┄'
        GradientSteps    = [int[]]@(22, 28, 64, 106, 244)
        GradientType     = 'fg'
    }

    # 14. blood-moon — Dark red/vampire
    $Themes['blood-moon'] = @{
        AccentColor      = '124'
        AccentFormat     = 'bold'
        BorderColor      = '232'
        BorderFormat     = 'bold'
        HeaderBg         = 'black'
        HeaderFg         = '124'
        ModuleBg         = 'black'
        ModuleFg         = '88'
        VersionBg        = 'black'
        VersionFg        = '52'
        SyntaxFg         = 'white'
        SyntaxFormat     = 'none'
        DescriptionFg    = '88'
        ParamNameFg      = '124'
        ParamNameFormat  = 'bold'
        ParamTypeFg      = '88'
        ParamTypeFormat  = 'italic'
        ParamReqFg       = '160'
        ParamReqFormat   = 'bold,reverse'
        ParamDescFg      = 'gray'
        ExampleFg        = '124'
        DocsFg           = '160'
        DocsFormat       = 'underline'
        SectionChar      = '🥀'
        HeaderChar       = '🩸'
        BorderTop        = '☠━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━☠'
        BorderBottom     = '☠━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━☠'
        BorderMiddle     = '│'
        GradientSteps    = [int[]]@(232, 52, 88, 124, 160)
        GradientType     = 'fg'
    }

    # 15. retro-arcade — 80s synthwave
    $Themes['retro-arcade'] = @{
        AccentColor      = '201'
        AccentFormat     = 'bold'
        BorderColor      = '51'
        BorderFormat     = 'bold'
        HeaderBg         = 'black'
        HeaderFg         = '201'
        ModuleBg         = 'black'
        ModuleFg         = '93'
        VersionBg        = 'black'
        VersionFg        = '39'
        SyntaxFg         = 'white'
        SyntaxFormat     = 'none'
        DescriptionFg    = '93'
        ParamNameFg      = '201'
        ParamNameFormat  = 'bold'
        ParamTypeFg      = '39'
        ParamTypeFormat  = 'none'
        ParamReqFg       = '196'
        ParamReqFormat   = 'bold'
        ParamDescFg      = 'gray'
        ExampleFg        = '51'
        DocsFg           = '201'
        DocsFormat       = 'underline'
        SectionChar      = '🕹'
        HeaderChar       = '👾'
        BorderTop        = '⍇⍈⍇⍈⍇⍈⍇⍈⍇⍈⍇⍈⍇⍈⍇⍈⍇⍈⍇⍈⍇⍈⍇⍈⍇⍈⍇⍈⍇⍈⍇⍈⍇⍈⍇⍈⍇⍈⍇⍈⍇⍈⍇⍈'
        BorderBottom     = '⍇⍈⍇⍈⍇⍈⍇⍈⍇⍈⍇⍈⍇⍈⍇⍈⍇⍈⍇⍈⍇⍈⍇⍈⍇⍈⍇⍈⍇⍈⍇⍈⍇⍈⍇⍈⍇⍈⍇⍈⍇⍈⍇⍈'
        BorderMiddle     = '⍉'
        GradientSteps    = [int[]]@(196, 201, 93, 39)
        GradientType     = 'fg'
    }

    # 16. abyss — Deep ocean/trench
    $Themes['abyss'] = @{
        AccentColor      = '19'
        AccentFormat     = 'bold'
        BorderColor      = '232'
        BorderFormat     = 'none'
        HeaderBg         = 'black'
        HeaderFg         = '21'
        ModuleBg         = 'black'
        ModuleFg         = '18'
        VersionBg        = 'black'
        VersionFg        = '19'
        SyntaxFg         = 'white'
        SyntaxFormat     = 'none'
        DescriptionFg    = '18'
        ParamNameFg      = '21'
        ParamNameFormat  = 'bold'
        ParamTypeFg      = '19'
        ParamTypeFormat  = 'italic'
        ParamReqFg       = '17'
        ParamReqFormat   = 'bold'
        ParamDescFg      = 'gray'
        ExampleFg        = '19'
        DocsFg           = '21'
        DocsFormat       = 'underline'
        SectionChar      = '⦿'
        HeaderChar       = '⁘'
        BorderTop        = '⁙⁘⁙⁘⁙⁘⁙⁘⁙⁘⁙⁘⁙⁘⁙⁘⁙⁘⁙⁘⁙⁘⁙⁘⁙⁘⁙⁘⁙⁘⁙⁘⁙⁘⁙⁘⁙⁘⁙⁘⁙⁘'
        BorderBottom     = '⁙⁘⁙⁘⁙⁘⁙⁘⁙⁘⁙⁘⁙⁘⁙⁘⁙⁘⁙⁘⁙⁘⁙⁘⁙⁘⁙⁘⁙⁘⁙⁘⁙⁘⁙⁘⁙⁘⁙⁘⁙⁘'
        BorderMiddle     = '⁛'
        GradientSteps    = [int[]]@(232, 17, 18, 19, 21)
        GradientType     = 'fg'
    }

    # 17. zen — Minimalist Japanese
    $Themes['zen'] = @{
        AccentColor      = '235'
        AccentFormat     = 'bold'
        BorderColor      = '248'
        BorderFormat     = 'none'
        HeaderBg         = 'black'
        HeaderFg         = '248'
        ModuleBg         = 'black'
        ModuleFg         = '245'
        VersionBg        = 'black'
        VersionFg        = '252'
        SyntaxFg         = 'white'
        SyntaxFormat     = 'none'
        DescriptionFg    = '245'
        ParamNameFg      = '248'
        ParamNameFormat  = 'bold'
        ParamTypeFg      = '245'
        ParamTypeFormat  = 'none'
        ParamReqFg       = '235'
        ParamReqFormat   = 'bold'
        ParamDescFg      = 'gray'
        ExampleFg        = '252'
        DocsFg           = '248'
        DocsFormat       = 'underline'
        SectionChar      = '⛩'
        HeaderChar       = '☯'
        BorderTop        = '◯────────────────────────────────────────────────────────◯'
        BorderBottom     = '◯────────────────────────────────────────────────────────◯'
        BorderMiddle     = '◦'
        GradientSteps    = [int[]]@(245, 248, 252, 255)
        GradientType     = 'fg'
    }

    # 18. blaze — Intense fire
    $Themes['blaze'] = @{
        AccentColor      = '208'
        AccentFormat     = 'bold'
        BorderColor      = '166'
        BorderFormat     = 'bold'
        HeaderBg         = 'black'
        HeaderFg         = '220'
        ModuleBg         = 'black'
        ModuleFg         = '208'
        VersionBg        = 'black'
        VersionFg        = '196'
        SyntaxFg         = 'white'
        SyntaxFormat     = 'none'
        DescriptionFg    = '208'
        ParamNameFg      = '220'
        ParamNameFormat  = 'bold'
        ParamTypeFg      = '208'
        ParamTypeFormat  = 'italic'
        ParamReqFg       = '196'
        ParamReqFormat   = 'bold,reverse'
        ParamDescFg      = 'gray'
        ExampleFg        = '202'
        DocsFg           = '220'
        DocsFormat       = 'underline'
        SectionChar      = '☄'
        HeaderChar       = '🔥'
        BorderTop        = '♨━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━♨'
        BorderBottom     = '♨━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━♨'
        BorderMiddle     = '🔥'
        GradientSteps    = [int[]]@(196, 202, 208, 214, 220)
        GradientType     = 'fg'
    }

    # 19. rust — Industrial decay
    $Themes['rust'] = @{
        AccentColor      = '130'
        AccentFormat     = 'bold'
        BorderColor      = '240'
        BorderFormat     = 'none'
        HeaderBg         = 'black'
        HeaderFg         = '130'
        ModuleBg         = 'black'
        ModuleFg         = '94'
        VersionBg        = 'black'
        VersionFg        = '52'
        SyntaxFg         = 'white'
        SyntaxFormat     = 'none'
        DescriptionFg    = '94'
        ParamNameFg      = '130'
        ParamNameFormat  = 'bold'
        ParamTypeFg      = '94'
        ParamTypeFormat  = 'italic'
        ParamReqFg       = '166'
        ParamReqFormat   = 'bold'
        ParamDescFg      = 'gray'
        ExampleFg        = '130'
        DocsFg           = '166'
        DocsFormat       = 'underline'
        SectionChar      = '⚙'
        HeaderChar       = '⚒'
        BorderTop        = '❖━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━❖'
        BorderBottom     = '❖━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━❖'
        BorderMiddle     = '⚒'
        GradientSteps    = [int[]]@(52, 94, 130, 166)
        GradientType     = 'fg'
    }

    # 20. matrix-neon — Vibrant matrix
    $Themes['matrix-neon'] = @{
        AccentColor      = '46'
        AccentFormat     = 'bold'
        BorderColor      = '22'
        BorderFormat     = 'bold'
        HeaderBg         = 'black'
        HeaderFg         = '46'
        ModuleBg         = 'black'
        ModuleFg         = '34'
        VersionBg        = 'black'
        VersionFg        = '28'
        SyntaxFg         = 'white'
        SyntaxFormat     = 'none'
        DescriptionFg    = '34'
        ParamNameFg      = '46'
        ParamNameFormat  = 'bold'
        ParamTypeFg      = '34'
        ParamTypeFormat  = 'italic'
        ParamReqFg       = '40'
        ParamReqFormat   = 'reverse'
        ParamDescFg      = 'gray'
        ExampleFg        = '46'
        DocsFg           = '46'
        DocsFormat       = 'underline'
        SectionChar      = '⁙'
        HeaderChar       = '⁚'
        BorderTop        = '⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙'
        BorderBottom     = '⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙⁙'
        BorderMiddle     = '⁘'
        GradientSteps    = [int[]]@(22, 28, 34, 40, 46)
        GradientType     = 'fg'
    }

    # 21. quantum — Scientific/subatomic
    $Themes['quantum'] = @{
        AccentColor      = '81'
        AccentFormat     = 'bold'
        BorderColor      = '57'
        BorderFormat     = 'none'
        HeaderBg         = 'black'
        HeaderFg         = '81'
        ModuleBg         = 'black'
        ModuleFg         = '129'
        VersionBg        = 'black'
        VersionFg        = '93'
        SyntaxFg         = 'white'
        SyntaxFormat     = 'none'
        DescriptionFg    = '93'
        ParamNameFg      = '81'
        ParamNameFormat  = 'bold'
        ParamTypeFg      = '129'
        ParamTypeFormat  = 'none'
        ParamReqFg       = '57'
        ParamReqFormat   = 'bold'
        ParamDescFg      = 'gray'
        ExampleFg        = '93'
        DocsFg           = '81'
        DocsFormat       = 'underline'
        SectionChar      = '⬢'
        HeaderChar       = '⬟'
        BorderTop        = '⬢⬡⬢⬡⬢⬡⬢⬡⬢⬡⬢⬡⬢⬡⬢⬡⬢⬡⬢⬡⬢⬡⬢⬡⬢⬡⬢⬡⬢⬡⬢⬡⬢⬡⬢⬡⬢⬡⬢⬡⬢⬡⬢⬡⬢⬡⬢⬡⬢⬡⬢⬡⬢⬡⬢⬡⬢⬡'
        BorderBottom     = '⬢⬡⬢⬡⬢⬡⬢⬡⬢⬡⬢⬡⬢⬡⬢⬡⬢⬡⬢⬡⬢⬡⬢⬡⬢⬡⬢⬡⬢⬡⬢⬡⬢⬡⬢⬡⬢⬡⬢⬡⬢⬡⬢⬡⬢⬡⬢⬡⬢⬡⬢⬡⬢⬡⬢⬡⬢⬡'
        BorderMiddle     = '⬡'
        GradientSteps    = [int[]]@(57, 93, 129, 81)
        GradientType     = 'fg'
    }

    # 22. radioactive — Nuclear fallout
    $Themes['radioactive'] = @{
        AccentColor      = '190'
        AccentFormat     = 'bold'
        BorderColor      = '232'
        BorderFormat     = 'bold'
        HeaderBg         = 'black'
        HeaderFg         = '190'
        ModuleBg         = 'black'
        ModuleFg         = '226'
        VersionBg        = 'black'
        VersionFg        = '232'
        SyntaxFg         = 'white'
        SyntaxFormat     = 'none'
        DescriptionFg    = '190'
        ParamNameFg      = '226'
        ParamNameFormat  = 'bold'
        ParamTypeFg      = '190'
        ParamTypeFormat  = 'italic'
        ParamReqFg       = '190'
        ParamReqFormat   = 'bold,reverse'
        ParamDescFg      = 'gray'
        ExampleFg        = '190'
        DocsFg           = '226'
        DocsFormat       = 'underline'
        SectionChar      = '☣'
        HeaderChar       = '☢'
        BorderTop        = '☢━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━☢'
        BorderBottom     = '☢━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━☢'
        BorderMiddle     = '☣'
        GradientSteps    = [int[]]@(232, 190, 226, 190)
        GradientType     = 'fg'
    }

    # 23. vaporwave — Pink/teal grid
    $Themes['vaporwave'] = @{
        AccentColor      = '201'
        AccentFormat     = 'bold'
        BorderColor      = '51'
        BorderFormat     = 'bold'
        HeaderBg         = 'black'
        HeaderFg         = '201'
        ModuleBg         = 'black'
        ModuleFg         = '165'
        VersionBg        = 'black'
        VersionFg        = '51'
        SyntaxFg         = 'white'
        SyntaxFormat     = 'none'
        DescriptionFg    = '165'
        ParamNameFg      = '201'
        ParamNameFormat  = 'bold'
        ParamTypeFg      = '51'
        ParamTypeFormat  = 'none'
        ParamReqFg       = '201'
        ParamReqFormat   = 'reverse'
        ParamDescFg      = 'gray'
        ExampleFg        = '51'
        DocsFg           = '201'
        DocsFormat       = 'underline'
        SectionChar      = '🌴'
        HeaderChar       = '🐬'
        BorderTop        = '▲▽▲▽▲▽▲▽▲▽▲▽▲▽▲▽▲▽▲▽▲▽▲▽▲▽▲▽▲▽▲▽▲▽▲▽▲▽▲▽▲▽▲▽▲▽▲▽▲▽▲▽▲▽▲▽▲▽▲▽▲▽▲▽▲▽▲▽▲▽'
        BorderBottom     = '▲▽▲▽▲▽▲▽▲▽▲▽▲▽▲▽▲▽▲▽▲▽▲▽▲▽▲▽▲▽▲▽▲▽▲▽▲▽▲▽▲▽▲▽▲▽▲▽▲▽▲▽▲▽▲▽▲▽▲▽▲▽▲▽▲▽▲▽▲▽'
        BorderMiddle     = '▽'
        GradientSteps    = [int[]]@(201, 165, 129, 81, 51)
        GradientType     = 'fg'
    }

    # 24. nebula — Bright violet/pink space
    $Themes['nebula'] = @{
        AccentColor      = '135'
        AccentFormat     = 'bold'
        BorderColor      = '163'
        BorderFormat     = 'none'
        HeaderBg         = 'black'
        HeaderFg         = '201'
        ModuleBg         = 'black'
        ModuleFg         = '135'
        VersionBg        = 'black'
        VersionFg        = '163'
        SyntaxFg         = 'white'
        SyntaxFormat     = 'none'
        DescriptionFg    = '135'
        ParamNameFg      = '201'
        ParamNameFormat  = 'bold'
        ParamTypeFg      = '163'
        ParamTypeFormat  = 'italic'
        ParamReqFg       = '129'
        ParamReqFormat   = 'bold'
        ParamDescFg      = 'gray'
        ExampleFg        = '135'
        DocsFg           = '201'
        DocsFormat       = 'underline'
        SectionChar      = '✹'
        HeaderChar       = '✸'
        BorderTop        = '❇❈❇❈❇❈❇❈❇❈❇❈❇❈❇❈❇❈❇❈❇❈❇❈❇❈❇❈❇❈❇❈❇❈❇❈❇❈❇❈❇❈❇❈❇❈❇❈❇❈❇❈❇❈❇❈❇❈'
        BorderBottom     = '❇❈❇❈❇❈❇❈❇❈❇❈❇❈❇❈❇❈❇❈❇❈❇❈❇❈❇❈❇❈❇❈❇❈❇❈❇❈❇❈❇❈❇❈❇❈❇❈❇❈❇❈❇❈❇❈❇❈'
        BorderMiddle     = '❇'
        GradientSteps    = [int[]]@(129, 135, 163, 199, 201)
        GradientType     = 'fg'
    }

    # 25. crystal — Diamond ice
    $Themes['crystal'] = @{
        AccentColor      = '195'
        AccentFormat     = 'bold'
        BorderColor      = '159'
        BorderFormat     = 'none'
        HeaderBg         = 'black'
        HeaderFg         = '255'
        ModuleBg         = 'black'
        ModuleFg         = '195'
        VersionBg        = 'black'
        VersionFg        = '159'
        SyntaxFg         = 'white'
        SyntaxFormat     = 'none'
        DescriptionFg    = '195'
        ParamNameFg      = '255'
        ParamNameFormat  = 'bold'
        ParamTypeFg      = '159'
        ParamTypeFormat  = 'none'
        ParamReqFg       = '195'
        ParamReqFormat   = 'bold'
        ParamDescFg      = 'gray'
        ExampleFg        = '159'
        DocsFg           = '255'
        DocsFormat       = 'underline'
        SectionChar      = '❖'
        HeaderChar       = '✧'
        BorderTop        = '❄❅❆❄❅❆❄❅❆❄❅❆❄❅❆❄❅❆❄❅❆❄❅❆❄❅❆❄❅❆❄❅❆❄❅❆❄❅❆❄❅❆❄❅❆❄❅❆❄❅❆❄❅❆❄❅❆'
        BorderBottom     = '❄❅❆❄❅❆❄❅❆❄❅❆❄❅❆❄❅❆❄❅❆❄❅❆❄❅❆❄❅❆❄❅❆❄❅❆❄❅❆❄❅❆❄❅❆❄❅❆❄❅❆❄❅❆❄❅❆'
        BorderMiddle     = '❅'
        GradientSteps    = [int[]]@(159, 195, 231, 255)
        GradientType     = 'fg'
    }

    # 26. copper — Copper piping
    $Themes['copper'] = @{
        AccentColor      = '130'
        AccentFormat     = 'bold'
        BorderColor      = '240'
        BorderFormat     = 'none'
        HeaderBg         = 'black'
        HeaderFg         = '214'
        ModuleBg         = 'black'
        ModuleFg         = '136'
        VersionBg        = 'black'
        VersionFg        = '130'
        SyntaxFg         = 'white'
        SyntaxFormat     = 'none'
        DescriptionFg    = '136'
        ParamNameFg      = '214'
        ParamNameFormat  = 'bold'
        ParamTypeFg      = '130'
        ParamTypeFormat  = 'italic'
        ParamReqFg       = '172'
        ParamReqFormat   = 'bold'
        ParamDescFg      = 'gray'
        ExampleFg        = '130'
        DocsFg           = '214'
        DocsFormat       = 'underline'
        SectionChar      = '╞'
        HeaderChar       = '╡'
        BorderTop        = '╞═╪═╡╞═╪═╡╞═╪═╡╞═╪═╡╞═╪═╡╞═╪═╡╞═╪═╡╞═╪═╡╞═╪═╡╞═╪═╡╞═╪═╡╞═╪═╡╞═╪═╡'
        BorderBottom     = '╞═╪═╡╞═╪═╡╞═╪═╡╞═╪═╡╞═╪═╡╞═╪═╡╞═╪═╡╞═╪═╡╞═╪═╡╞═╪═╡╞═╪═╡╞═╪═╡╞═╪═╡'
        BorderMiddle     = '╪'
        GradientSteps    = [int[]]@(130, 136, 172, 214)
        GradientType     = 'fg'
    }

    # 27. royal — Gold on royal blue
    $Themes['royal'] = @{
        AccentColor      = '220'
        AccentFormat     = 'bold'
        BorderColor      = '20'
        BorderFormat     = 'bold'
        HeaderBg         = 'black'
        HeaderFg         = '226'
        ModuleBg         = 'black'
        ModuleFg         = '20'
        VersionBg        = 'black'
        VersionFg        = '220'
        SyntaxFg         = 'white'
        SyntaxFormat     = 'none'
        DescriptionFg    = '20'
        ParamNameFg      = '226'
        ParamNameFormat  = 'bold'
        ParamTypeFg      = '220'
        ParamTypeFormat  = 'italic'
        ParamReqFg       = '20'
        ParamReqFormat   = 'bold,reverse'
        ParamDescFg      = 'gray'
        ExampleFg        = '220'
        DocsFg           = '226'
        DocsFormat       = 'underline'
        SectionChar      = '⚜'
        HeaderChar       = '✦'
        BorderTop        = '❂━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━❂'
        BorderBottom     = '❂━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━❂'
        BorderMiddle     = '⚜'
        GradientSteps    = [int[]]@(17, 20, 21, 220, 226)
        GradientType     = 'fg'
    }

    # 28. desert-heat — Warm yellow/red
    $Themes['desert-heat'] = @{
        AccentColor      = '214'
        AccentFormat     = 'bold'
        BorderColor      = '130'
        BorderFormat     = 'none'
        HeaderBg         = 'black'
        HeaderFg         = '220'
        ModuleBg         = 'black'
        ModuleFg         = '202'
        VersionBg        = 'black'
        VersionFg        = '130'
        SyntaxFg         = 'white'
        SyntaxFormat     = 'none'
        DescriptionFg    = '202'
        ParamNameFg      = '220'
        ParamNameFormat  = 'bold'
        ParamTypeFg      = '130'
        ParamTypeFormat  = 'italic'
        ParamReqFg       = '196'
        ParamReqFormat   = 'bold'
        ParamDescFg      = 'gray'
        ExampleFg        = '214'
        DocsFg           = '220'
        DocsFormat       = 'underline'
        SectionChar      = '☀'
        HeaderChar       = '🏜'
        BorderTop        = '☀━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━☀'
        BorderBottom     = '☀━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━☀'
        BorderMiddle     = '▒'
        GradientSteps    = [int[]]@(130, 166, 202, 214, 220)
        GradientType     = 'fg'
    }

    # 29. sheriff — Western brown/tan
    $Themes['sheriff'] = @{
        AccentColor      = '94'
        AccentFormat     = 'bold'
        BorderColor      = '137'
        BorderFormat     = 'none'
        HeaderBg         = 'black'
        HeaderFg         = '137'
        ModuleBg         = 'black'
        ModuleFg         = '94'
        VersionBg        = 'black'
        VersionFg        = '180'
        SyntaxFg         = 'white'
        SyntaxFormat     = 'none'
        DescriptionFg    = '94'
        ParamNameFg      = '137'
        ParamNameFormat  = 'bold'
        ParamTypeFg      = '94'
        ParamTypeFormat  = 'none'
        ParamReqFg       = '180'
        ParamReqFormat   = 'bold'
        ParamDescFg      = 'gray'
        ExampleFg        = '137'
        DocsFg           = '137'
        DocsFormat       = 'underline'
        SectionChar      = '✶'
        HeaderChar       = '↱'
        BorderTop        = '╙─╨─╜╙─╨─╜╙─╨─╜╙─╨─╜╙─╨─╜╙─╨─╜╙─╨─╜╙─╨─╜╙─╨─╜╙─╨─╜╙─╨─╜╙─╨─╜╙─╨─╜'
        BorderBottom     = '╙─╨─╜╙─╨─╜╙─╨─╜╙─╨─╜╙─╨─╜╙─╨─╜╙─╨─╜╙─╨─╜╙─╨─╜╙─╨─╜╙─╨─╜╙─╨─╜╙─╨─╜'
        BorderMiddle     = '─'
        GradientSteps    = [int[]]@(52, 94, 137, 180)
        GradientType     = 'fg'
    }

    # 30. frost — Arctic cold
    $Themes['frost'] = @{
        AccentColor      = '117'
        AccentFormat     = 'bold'
        BorderColor      = '240'
        BorderFormat     = 'none'
        HeaderBg         = 'black'
        HeaderFg         = '159'
        ModuleBg         = 'black'
        ModuleFg         = '117'
        VersionBg        = 'black'
        VersionFg        = '248'
        SyntaxFg         = 'white'
        SyntaxFormat     = 'none'
        DescriptionFg    = '244'
        ParamNameFg      = '159'
        ParamNameFormat  = 'bold'
        ParamTypeFg      = '117'
        ParamTypeFormat  = 'italic'
        ParamReqFg       = '159'
        ParamReqFormat   = 'bold'
        ParamDescFg      = 'gray'
        ExampleFg        = '117'
        DocsFg           = '159'
        DocsFormat       = 'underline'
        SectionChar      = '❄'
        HeaderChar       = '❆'
        BorderTop        = '┋ ❄ ┋ ❄ ┋ ❄ ┋ ❄ ┋ ❄ ┋ ❄ ┋ ❄ ┋ ❄ ┋ ❄ ┋ ❄ ┋ ❄ ┋ ❄ ┋ ❄ ┋ ❄ ┋ ❄ ┋ ❄ ┋'
        BorderBottom     = '┋ ❄ ┋ ❄ ┋ ❄ ┋ ❄ ┋ ❄ ┋ ❄ ┋ ❄ ┋ ❄ ┋ ❄ ┋ ❄ ┋ ❄ ┋ ❄ ┋ ❄ ┋ ❄ ┋ ❄ ┋ ❄ ┋'
        BorderMiddle     = '┋'
        GradientSteps    = [int[]]@(240, 244, 248, 117, 159)
        GradientType     = 'fg'
    }

    # 10. phwriter — The original PHWriter retro theme (restored as a named theme)
    $Themes['phwriter'] = @{
        AccentColor      = 'darkcyan'
        AccentFormat     = 'bold'
        BorderColor      = 'darkgreen'
        BorderFormat     = 'bold'
        HeaderBg         = ''
        HeaderFg         = 'cyan'
        ModuleBg         = ''
        ModuleFg         = 'cyan'
        VersionBg        = ''
        VersionFg        = 'cyan'
        SyntaxFg         = 'white'
        SyntaxFormat     = 'none'
        DescriptionFg    = 'white'
        ParamNameFg      = 'green'
        ParamNameFormat  = 'bold'
        ParamTypeFg      = 'darkcyan'
        ParamTypeFormat  = 'none'
        ParamReqFg       = 'red'
        ParamReqFormat   = 'bold'
        ParamDescFg      = 'gray'
        ExampleFg        = 'yellow'
        DocsFg           = 'darkcyan'
        DocsFormat       = 'bold,underline'
        SectionChar      = '◉'
        HeaderChar       = '▶'
        BorderTop        = '══════════════════════════════════════════════════════════════'
        BorderBottom     = '══════════════════════════════════════════════════════════════'
        BorderMiddle     = '░'
    }

    # phman is an alias for the phwriter theme
    $Themes['phman'] = $Themes['phwriter']

    # ── 10 New Hard-Bordered Themes using ASCII shapes ───────────────────────────

    # 1. drift-blue-orange — Reserved themed with double border and blue/orange colors
    $Themes['drift-blue-orange'] = @{
        AccentColor      = '39'          # Sky blue
        AccentFormat     = 'bold'
        BorderColor      = '208'         # Bright orange
        BorderFormat     = 'bold'
        HeaderBg         = ''
        HeaderFg         = '39'
        ModuleBg         = ''
        ModuleFg         = '39'
        VersionBg        = ''
        VersionFg        = '208'
        SyntaxFg         = 'white'
        SyntaxFormat     = 'none'
        DescriptionFg    = 'white'
        ParamNameFg      = '39'
        ParamNameFormat  = 'bold'
        ParamTypeFg      = '208'
        ParamTypeFormat  = 'none'
        ParamReqFg       = 'red'
        ParamReqFormat   = 'bold'
        ParamDescFg      = 'gray'
        ExampleFg        = '39'
        DocsFg           = '208'
        DocsFormat       = 'bold,underline'
        SectionChar      = '◆'
        HeaderChar       = '▶'
        BorderTop        = '╔══════════════════════════════════════════════════════════════╗'
        BorderBottom     = '╚══════════════════════════════════════════════════════════════╝'
        BorderMiddle     = '║'
    }

    # 2. steel-plate — Heavy industrial single line box borders with steel gray palette
    $Themes['steel-plate'] = @{
        AccentColor      = 'white'
        AccentFormat     = 'bold'
        BorderColor      = '245'         # Steel gray
        BorderFormat     = 'bold'
        HeaderBg         = ''
        HeaderFg         = 'white'
        ModuleBg         = ''
        ModuleFg         = 'white'
        VersionBg        = ''
        VersionFg        = '245'
        SyntaxFg         = '250'
        SyntaxFormat     = 'none'
        DescriptionFg    = '252'
        ParamNameFg      = 'white'
        ParamNameFormat  = 'bold'
        ParamTypeFg      = '245'
        ParamTypeFormat  = 'italic'
        ParamReqFg       = '203'
        ParamReqFormat   = 'bold'
        ParamDescFg      = '244'
        ExampleFg        = 'white'
        DocsFg           = '245'
        DocsFormat       = 'underline'
        SectionChar      = '█'
        HeaderChar       = '▌'
        BorderTop        = '▛▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▜'
        BorderBottom     = '▙▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▟'
        BorderMiddle     = '▌'
    }

    # 3. cyber-grid — Grid block patterned borders with cyber magenta/yellow colors
    $Themes['cyber-grid'] = @{
        AccentColor      = '226'         # Yellow
        AccentFormat     = 'bold'
        BorderColor      = '201'         # Cyber pink/magenta
        BorderFormat     = 'bold'
        HeaderBg         = ''
        HeaderFg         = '226'
        ModuleBg         = ''
        ModuleFg         = '201'
        VersionBg        = ''
        VersionFg        = '226'
        SyntaxFg         = 'white'
        SyntaxFormat     = 'none'
        DescriptionFg    = '226'
        ParamNameFg      = '201'
        ParamNameFormat  = 'bold'
        ParamTypeFg      = '51'          # Cyan
        ParamTypeFormat  = 'none'
        ParamReqFg       = '196'
        ParamReqFormat   = 'bold'
        ParamDescFg      = 'gray'
        ExampleFg        = '226'
        DocsFg           = '51'
        DocsFormat       = 'underline'
        SectionChar      = '▩'
        HeaderChar       = '▨'
        BorderTop        = '▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩'
        BorderBottom     = '▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩'
        BorderMiddle     = '▩'
    }

    # 4. retro-blocks — Classic solid blocks and squares border style
    $Themes['retro-blocks'] = @{
        AccentColor      = '81'          # Retro light blue
        AccentFormat     = 'bold'
        BorderColor      = '15'          # White
        BorderFormat     = 'none'
        HeaderBg         = ''
        HeaderFg         = '81'
        ModuleBg         = ''
        ModuleFg         = '15'
        VersionBg        = ''
        VersionFg        = '81'
        SyntaxFg         = 'white'
        SyntaxFormat     = 'none'
        DescriptionFg    = '250'
        ParamNameFg      = '81'
        ParamNameFormat  = 'bold'
        ParamTypeFg      = '15'
        ParamTypeFormat  = 'none'
        ParamReqFg       = '196'
        ParamReqFormat   = 'bold'
        ParamDescFg      = 'gray'
        ExampleFg        = '81'
        DocsFg           = '15'
        DocsFormat       = 'underline'
        SectionChar      = '■'
        HeaderChar       = '▪'
        BorderTop        = '■□■□■□■□■□■□■□■□■□■□■□■□■□■□■□■□■□■□■□■□■□■□■□■□■□■□■□■□■□■□'
        BorderBottom     = '■□■□■□■□■□■□■□■□■□■□■□■□■□■□■□■□■□■□■□■□■□■□■□■□■□■□■□■□■□■□'
        BorderMiddle     = '▪'
    }

    # 5. gothic-crypt — Dark red and gothic cross shape styling
    $Themes['gothic-crypt'] = @{
        AccentColor      = '196'         # Crimson
        AccentFormat     = 'bold'
        BorderColor      = '88'          # Dark red
        BorderFormat     = 'bold'
        HeaderBg         = ''
        HeaderFg         = '196'
        ModuleBg         = ''
        ModuleFg         = '88'
        VersionBg        = ''
        VersionFg        = '196'
        SyntaxFg         = '250'
        SyntaxFormat     = 'none'
        DescriptionFg    = 'gray'
        ParamNameFg      = '196'
        ParamNameFormat  = 'bold'
        ParamTypeFg      = '88'
        ParamTypeFormat  = 'italic'
        ParamReqFg       = '196'
        ParamReqFormat   = 'bold'
        ParamDescFg      = 'gray'
        ExampleFg        = '196'
        DocsFg           = '88'
        DocsFormat       = 'underline'
        SectionChar      = '☩'
        HeaderChar       = '♰'
        BorderTop        = '☩━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━☩'
        BorderBottom     = '☩━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━☩'
        BorderMiddle     = '│'
    }

    # 6. acid-shards — Triangles and shards with toxic yellow/green tones
    $Themes['acid-shards'] = @{
        AccentColor      = '190'         # Lime yellow
        AccentFormat     = 'bold'
        BorderColor      = '112'         # Toxic green
        BorderFormat     = 'bold'
        HeaderBg         = ''
        HeaderFg         = '190'
        ModuleBg         = ''
        ModuleFg         = '112'
        VersionBg        = ''
        VersionFg        = '190'
        SyntaxFg         = 'white'
        SyntaxFormat     = 'none'
        DescriptionFg    = '190'
        ParamNameFg      = '112'
        ParamNameFormat  = 'bold'
        ParamTypeFg      = '190'
        ParamTypeFormat  = 'none'
        ParamReqFg       = '196'
        ParamReqFormat   = 'bold'
        ParamDescFg      = 'gray'
        ExampleFg        = '190'
        DocsFg           = '112'
        DocsFormat       = 'underline'
        SectionChar      = '▼'
        HeaderChar       = '▲'
        BorderTop        = '▼△▼△▼△▼△▼△▼△▼△▼△▼△▼△▼△▼△▼△▼△▼△▼△▼△▼△▼△▼△▼△▼△▼△▼△▼△▼△▼△▼△▼△▼△'
        BorderBottom     = '▲▽▲▽▲▽▲▽▲▽▲▽▲▽▲▽▲▽▲▽▲▽▲▽▲▽▲▽▲▽▲▽▲▽▲▽▲▽▲▽▲▽▲▽▲▽▲▽▲▽▲▽▲▽▲▽▲▽▲▽'
        BorderMiddle     = '▲'
    }

    # 7. aurora-borealis — Rounded single box corners with blue/green gradient
    $Themes['aurora-borealis'] = @{
        AccentColor      = '51'          # Bright Cyan
        AccentFormat     = 'bold'
        BorderColor      = '33'          # Royal Blue
        BorderFormat     = 'none'
        HeaderBg         = ''
        HeaderFg         = '51'
        ModuleBg         = ''
        ModuleFg         = '33'
        VersionBg        = ''
        VersionFg        = '201'         # Aurora purple accent
        SyntaxFg         = 'white'
        SyntaxFormat     = 'none'
        DescriptionFg    = 'white'
        ParamNameFg      = '51'
        ParamNameFormat  = 'bold'
        ParamTypeFg      = '201'
        ParamTypeFormat  = 'italic'
        ParamReqFg       = '196'
        ParamReqFormat   = 'bold'
        ParamDescFg      = 'gray'
        ExampleFg        = '51'
        DocsFg           = '201'
        DocsFormat       = 'underline'
        SectionChar      = '❄'
        HeaderChar       = '│'
        BorderTop        = '╭────────────────────────────────────────────────────────────╮'
        BorderBottom     = '╰────────────────────────────────────────────────────────────╯'
        BorderMiddle     = '│'
        GradientSteps    = [int[]]@(51, 45, 129, 201, 207)
        GradientType     = 'fg'
    }

    # 8. solar-flare — Diamonds border shapes with burning orange/gold colors
    $Themes['solar-flare'] = @{
        AccentColor      = '220'         # Bright Gold
        AccentFormat     = 'bold'
        BorderColor      = '202'         # Fire Orange
        BorderFormat     = 'bold'
        HeaderBg         = ''
        HeaderFg         = '220'
        ModuleBg         = ''
        ModuleFg         = '202'
        VersionBg        = ''
        VersionFg        = '220'
        SyntaxFg         = 'white'
        SyntaxFormat     = 'none'
        DescriptionFg    = '220'
        ParamNameFg      = '202'
        ParamNameFormat  = 'bold'
        ParamTypeFg      = '220'
        ParamTypeFormat  = 'none'
        ParamReqFg       = '196'
        ParamReqFormat   = 'bold'
        ParamDescFg      = 'gray'
        ExampleFg        = '220'
        DocsFg           = '202'
        DocsFormat       = 'underline'
        SectionChar      = '◆'
        HeaderChar       = '◈'
        BorderTop        = '◆◇◆◇◆◇◆◇◆◇◆◇◆◇◆◇◆◇◆◇◆◇◆◇◆◇◆◇◆◇◆◇◆◇◆◇◆◇◆◇◆◇◆◇◆◇◆◇◆◇◆◇◆◇◆◇◆◇◆◇'
        BorderBottom     = '◆◇◆◇◆◇◆◇◆◇◆◇◆◇◆◇◆◇◆◇◆◇◆◇◆◇◆◇◆◇◆◇◆◇◆◇◆◇◆◇◆◇◆◇◆◇◆◇◆◇◆◇◆◇◆◇◆◇◆◇'
        BorderMiddle     = '◈'
    }

    # 9. subspace — Double heavy arrowheads and deep space teal colors
    $Themes['subspace'] = @{
        AccentColor      = '39'          # Teal
        AccentFormat     = 'bold'
        BorderColor      = '24'          # Dark Blue
        BorderFormat     = 'bold'
        HeaderBg         = ''
        HeaderFg         = '39'
        ModuleBg         = ''
        ModuleFg         = '24'
        VersionBg        = ''
        VersionFg        = '39'
        SyntaxFg         = 'white'
        SyntaxFormat     = 'none'
        DescriptionFg    = 'gray'
        ParamNameFg      = '39'
        ParamNameFormat  = 'bold'
        ParamTypeFg      = '24'
        ParamTypeFormat  = 'italic'
        ParamReqFg       = '196'
        ParamReqFormat   = 'bold'
        ParamDescFg      = 'gray'
        ExampleFg        = '39'
        DocsFg           = '24'
        DocsFormat       = 'underline'
        SectionChar      = '⇛'
        HeaderChar       = '┃'
        BorderTop        = '⇛━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━⇚'
        BorderBottom     = '⇛━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━⇚'
        BorderMiddle     = '┃'
    }

    # 10. neon-horizon — Blocks and shades with hot pink/cyan horizon styling
    $Themes['neon-horizon'] = @{
        AccentColor      = '201'         # Hot Pink
        AccentFormat     = 'bold'
        BorderColor      = '51'          # Neon Cyan
        BorderFormat     = 'bold'
        HeaderBg         = ''
        HeaderFg         = '201'
        ModuleBg         = ''
        ModuleFg         = '51'
        VersionBg        = ''
        VersionFg        = '201'
        SyntaxFg         = 'white'
        SyntaxFormat     = 'none'
        DescriptionFg    = 'white'
        ParamNameFg      = '51'
        ParamNameFormat  = 'bold'
        ParamTypeFg      = '201'
        ParamTypeFormat  = 'none'
        ParamReqFg       = '196'
        ParamReqFormat   = 'bold'
        ParamDescFg      = 'gray'
        ExampleFg        = '201'
        DocsFg           = '51'
        DocsFormat       = 'underline'
        SectionChar      = '█'
        HeaderChar       = '░'
        BorderTop        = '░▒▓█▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀█▓▒░'
        BorderBottom     = '░▒▓█▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄█▓▒░'
        BorderMiddle     = '█'
    }

    # ── Lookup and return ─────────────────────────────────────────────────────
    $selected = $Name.ToLower()
    if ($Themes.ContainsKey($selected)) {
        return $Themes[$selected]
    }
    return $Themes['default']
}

function Format-ThemeText {
    param(
        [string]$String,
        [hashtable]$Theme,
        [string]$Element
    )
    if ([string]::IsNullOrEmpty($String)) { return '' }

    $colorKey  = "${Element}Fg"
    $bgKey     = "${Element}Bg"
    $formatKey = "${Element}Format"

    $color   = if ($Theme.ContainsKey($colorKey))  { $Theme[$colorKey]  } else { '' }
    $bgColor = if ($Theme.ContainsKey($bgKey))      { $Theme[$bgKey]     } else { '' }

    $rawFormat = if ($Theme.ContainsKey($formatKey)) {
        if ($Theme[$formatKey] -is [array]) { $Theme[$formatKey] }
        else { $Theme[$formatKey] -split ',' }
    } else { @() }

    $format = @($rawFormat) | Where-Object { $_ -and $_ -ne 'none' }

    $params = @{
        String  = $String
        Color   = $color
        BgColor = $bgColor
    }
    if ($format -and $format.Count -gt 0) {
        $params['Format'] = $format
    }

    return New-AsciiColor @params
}
