<#
.SYNOPSIS
Generates one VHS tape for every selectable PHWriter theme.

.DESCRIPTION
Reads the ValidateSet from Show-PHTheme so the generated tapes remain aligned
with the public command contract. Each tape renders one presentation variant to
docs/assets/themes-previews/<theme>/<variant>.gif.

.PARAMETER OutputDirectory
Directory that receives generated .tape files. Defaults to vhs/generated.
#>
[CmdletBinding()]
param(
    [string]$OutputDirectory
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$vhsDirectory = $PSScriptRoot
$repositoryRoot = [System.IO.Directory]::GetParent($vhsDirectory).FullName
$moduleManifest = [System.IO.Path]::Combine($repositoryRoot, 'phwriter.psd1')

if ([string]::IsNullOrWhiteSpace($OutputDirectory)) {
    $OutputDirectory = [System.IO.Path]::Combine($vhsDirectory, 'generated')
}

Import-Module -Name $moduleManifest -Force
$nameParameter = (Get-Command -Name Show-PHTheme -ErrorAction Stop).Parameters['Name']
$validateSet = $nameParameter.Attributes | Where-Object { $_ -is [System.Management.Automation.ValidateSetAttribute] } | Select-Object -First 1
if ($null -eq $validateSet) {
    throw 'Show-PHTheme -Name no longer declares a ValidateSet.'
}

[System.IO.Directory]::CreateDirectory($OutputDirectory) | Out-Null
foreach ($existingTape in [System.IO.Directory]::EnumerateFiles($OutputDirectory, '*.tape')) {
    [System.IO.File]::Delete($existingTape)
}

$themeNames = $validateSet.ValidValues | Where-Object { $_ -notin @('all', 'custom-rgb') } | Sort-Object
$variantNames = @('Base', 'Rounded', 'Double', 'Gradient')
$previewRoot = [System.IO.Path]::Combine($repositoryRoot, 'docs', 'assets', 'themes-previews')

foreach ($themeName in $themeNames) {
    [System.IO.Directory]::CreateDirectory([System.IO.Path]::Combine($previewRoot, $themeName)) | Out-Null

    foreach ($variantName in $variantNames) {
        $variantSlug = $variantName.ToLowerInvariant()
        $tapePath = [System.IO.Path]::Combine($OutputDirectory, "$themeName-$variantSlug.tape")
        $tape = @"
# Generated by New-ThemeVariantTapes.ps1. Do not edit manually.
Output ../../docs/assets/themes-previews/$themeName/$variantSlug.gif

Set Shell "pwsh"
Set FontSize 14
Set Width 960
Set Height 600
Set Padding 16
Set Theme "Dracula"
Set WindowBar Colorful

Hide
Show

Type "pwsh -NoProfile -File ../Invoke-AllThemeVarients.ps1 -Theme '$themeName' -Variant '$variantName'" Enter
Sleep 2s
"@

        [System.IO.File]::WriteAllText($tapePath, $tape, [System.Text.UTF8Encoding]::new($false))
    }
}

Write-Host "Generated $($themeNames.Count * $variantNames.Count) theme-variant tapes in '$OutputDirectory'." -ForegroundColor Green
